### ISSUE TITLE
Consistent terminology and notation

### ISSUE THREAD

**Issue by ugurdogrusoz** [metincansiper/newt#1]
Let's change, as agreed, protein with macromolecule and small molecule with simple chemical for a consistent terminology in all palettes/map types.
I forget if we discussed this but I propose to change the shape for simple chemicals to be the same as PD as well (ellipse). This way they will be easier to differentiate. What do you think @ozgunbabur?

**Comment by ozgunbabur** [comment]
Sounds good.

**Comment by metincansiper** [comment]
@ugurdogrusoz is what do you mean only renaming them in palette or treating them as small molecule/simple chemical too?

For example currently compartments are available in both PD and AF palettes. PD and AF compartments refers to the same thing they have exactly the same type. They share the same default values, and so it is no matter if you change default properties of a compartment from PD or AF palette. Do you mean something like that or still having different types but just naming them as small molecule/simple chemical in palette?

**Comment by ugurdogrusoz** [comment]
I am not sure what you mean by treating them as small molecule. Everywhere in the user interface as well as code, we should refer to small molecules as simple chemicals for consistency.
Regarding types/classes, lets keep doing what we were doing. If two compartments in two different palettes are named the same, let's name them the same.

**Comment by metincansiper** [comment]
I think I can better say "using the small molecule class" for them instead of "treating them as small molecule". It actually means totally get rid of "protein" and "macromolecule", using "macromolecule" and "simple chemical" instead. 

However, there is one thing behind doing so. Currently, for protein and small molecule there are some specific default properties. For example they have bigger infoboxes and infobox texts by default etc. When we do so we will be using the same default values for them and "macromolecule" and "simple chemical" respectively (actually this is inevitable since there will no more be protein and small molecule classes). Therefore, default values needs to be re-evaluated before making that change.

**Comment by ugurdogrusoz** [comment]
Let's consistently use the name:
- "Macromolecule" or "SIF Macromolecule"
- "Simple Chemical" or "SIF Simple Chemical"
as appropriate in the GUI.
Internally these could be different classes with varying default style (e.g. larger infoboxes).

**Comment by ugurdogrusoz** [comment]
Unless there is a good reason for it, how about making the default dimension of simple chemicals in SIF to be consistent with the PD view?

**Comment by metincansiper** [comment]
>Unless there is a good reason for it, how about making the default dimension of simple chemicals in SIF to be consistent with the PD view?

@ozgunbabur what do you think?

**Comment by ozgunbabur** [comment]
Sounds fine to me.
